In [131]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [133]:
df = pd.read_csv(r"C:\Users\kelvi\Downloads\nairobi_property_listings.csv")

In [137]:
df.head()

,Listing_ID,Title,Location,Property_Type,Price_KES,Bedrooms,Bathrooms,Size_sqft,Agent,Contact
0,48e3aba8,Maisonette for Sale,Ngong Road,Maisonette,26272409,4,3,1662,PrimeSpace Ltd,254740231444
1,3b6f2578,Apartment for Sale,Karen,Townhouse,3387854,5,3,1297,Safari Estates,254736575274
2,f5526dfb,Maisonette for Sale,Lang'ata,Bungalow,40724451,2,1,3603,Horizon Homes,254749431878
3,c893b9d6,Townhouse for Sale,South C,Studio,49340384,1,2,4378,Metro Property,254784392364
4,89913fb2,Townhouse for Sale,Westlands,Maisonette,20070868,5,4,1088,Safari Estates,254719837181

In [139]:
df.shape

(800, 10)

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Listing_ID     800 non-null    object
 1   Title          800 non-null    object
 2   Location       800 non-null    object
 3   Property_Type  800 non-null    object
 4   Price_KES      800 non-null    int64
 5   Bedrooms       800 non-null    int64
 6   Bathrooms      800 non-null    int64
 7   Size_sqft      800 non-null    int64
 8   Agent          800 non-null    object
 9   Contact        800 non-null    int64
dtypes: int64(5), object(5)
memory usage: 62.6+ KB

In [127]:
dataset = df

In [181]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(dataset,dataset['Price_KES'],test_size=0.1,random_state=0)

from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel

In [183]:
x_train.shape, x_test.shape

((720, 10), (80, 10))

In [ ]:
# there are no missing values

In [185]:
 x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 720 entries, 251 to 684
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Listing_ID     720 non-null    object
 1   Title          720 non-null    object
 2   Location       720 non-null    object
 3   Property_Type  720 non-null    object
 4   Price_KES      720 non-null    int64
 5   Bedrooms       720 non-null    int64
 6   Bathrooms      720 non-null    int64
 7   Size_sqft      720 non-null    int64
 8   Agent          720 non-null    object
 9   Contact        720 non-null    int64
dtypes: int64(5), object(5)
memory usage: 61.9+ KB

In [187]:
dataset2=x_train

In [189]:
dataset2.head()

,Listing_ID,Title,Location,Property_Type,Price_KES,Bedrooms,Bathrooms,Size_sqft,Agent,Contact
251,1efc58a1,Maisonette for Sale,Donholm,Townhouse,41783889,2,2,1104,UrbanNest Realty,254773663095
250,4a59616a,Townhouse for Sale,Ngong Road,Bungalow,73954912,1,2,4379,Horizon Homes,254767951367
390,0d0f9c11,Studio for Sale,Donholm,Townhouse,39693024,1,4,2940,Horizon Homes,254752663256
703,a5921f94,Apartment for Sale,Ngong Road,Studio,38307277,5,4,3462,Safari Estates,254710024206
386,f1ca0c77,Maisonette for Sale,Lavington,Apartment,13717491,4,3,2271,UrbanNest Realty,254724371130

In [191]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 720 entries, 251 to 684
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Listing_ID     720 non-null    object
 1   Title          720 non-null    object
 2   Location       720 non-null    object
 3   Property_Type  720 non-null    object
 4   Price_KES      720 non-null    int64
 5   Bedrooms       720 non-null    int64
 6   Bathrooms      720 non-null    int64
 7   Size_sqft      720 non-null    int64
 8   Agent          720 non-null    object
 9   Contact        720 non-null    int64
dtypes: int64(5), object(5)
memory usage: 61.9+ KB

In [155]:
y_train=dataset2[['Price_KES']]

In [157]:
 X_train=dataset.drop(['Listing_ID','Price_KES','Title','Location','Property_Type','Agent','Contact'],axis=1)

In [159]:
X_train.head()

   Bedrooms  Bathrooms  Size_sqft
0         4          3       1662
1         5          3       1297
2         2          1       3603
3         1          2       4378
4         5          4       1088

In [161]:
x_train = dataset.drop(['Listing_ID','Price_KES','Title','Location','Property_Type','Agent','Contact'],axis=1)

In [165]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Bedrooms   800 non-null    int64
 1   Bathrooms  800 non-null    int64
 2   Size_sqft  800 non-null    int64
dtypes: int64(3)
memory usage: 18.9 KB

In [167]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Bedrooms   800 non-null    int64
 1   Bathrooms  800 non-null    int64
 2   Size_sqft  800 non-null    int64
dtypes: int64(3)
memory usage: 18.9 KB

In [175]:
y_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 720 entries, 251 to 684
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price_KES  720 non-null    int64
dtypes: int64(1)
memory usage: 11.2 KB

In [173]:
dataset2 = dataset.drop(['Listing_ID','Price_KES','Title','Location','Property_Type','Agent','Contact'],axis=1)

In [171]:
sel_model = SelectFromModel(Lasso(alpha=0.005, random_state=0))
sel_model.fit(x_train,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [800, 720]